---
title: "A newbie in the KampalR community"
author: "Nelda"
date: 2019-07-05


links:
- icon: twitter
  icon_pack: fab
  name: Follow
  url: https://twitter.com/AfricaRUsers

images: []

categories:
  - community
  - community
tags:
  - community
  - kampalr
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

It’s been 2 years 3 months since I have been affiliated with the Kampala R User Group aka [`@KampalR`](https://twitter.com/kampalR?s=17)

# How it all started

Alas January, everyone is excited about the new year, resolutions flying East, West and everyone eager and anticipating a year of greatness. For some of us, especially when you have been over a year out of campus and into the real world, it’s a time to reflect and rethink what direction you want your life to take.
January 2018 was that turning point for me, I loved the course I pursued at the university however I found myself in communications & marketing, a completely different field from what I had ever envisioned I would be doing and so so far away from my passion and what I really wanted to get my hands on. 
That year I purposed to go back to my first love i.e computers and everything that comes along with it. That’s when the data science wave started sounding and sweeping over Uganda and after doing all the online research, I told myself this is it.
So the journey begins,
 <style>
body {text-align: justify}
</style>
# KampalR

Geared up, full tank I knew what I wanted so the next step was to find all the resources imaginable and start learning because over 2 years in communications had me on a totally new direction.
Checking up for meet-ups around the city and then I come across R user group, I didn’t have the slightest idea what R was, in fact to make myself feel better I imagined it was someone trying to fancy up a name for their meet-up. 
Either way I registered because guess what the description had an **Introduction to data science** and that’s what I wanted.
Walking into this room, I was the only lady in a room full of gentlemen and of course egos were flying, heads turning at this lady but I still sat (after-all it’s what I wanted, had to find a way to fit in). 
That weekend, we had a lady facilitator which was cool of course and after the session, there was a bottle of soda and pizza. My mind was fully made up to return (partly persuaded by the pizza but also the session and the community). 

Joining KampalR community has been one of the best decisions I made to jumpstart my data science 
career because despite the fact that I was the only lady for about 2 meet-ups before another lady 
stumbled in: Her Excellency Ms Shakyrah ([`@cynthia_kyra`](https://twitter.com/cynthia_kyra?s=17)), I didn’t feel left out.

The community oozes inclusion, energy, passion and a deep desire to groom some of the best R users in the country. The people make it more perfect because each person in the community goes an extra mile so that their neighbour learns and also make sure no one is left behind. 
The facilitators include everyone as much as possible and make the process to learn R as simple as possible.
It’s been 2 years since I joined the kampalR community, and I have not only learned R but also joined the force that makes this community meet-ups happen every month alongside [`@okello_mark`](https://twitter.com/okello_mark?s=17) as the lead and [`@cynthia_kyra`](https://twitter.com/cynthia_kyra?s=17) as a co-lead.

We have meet-ups organised at-least every month and always come up with interesting sessions to grow the community. 
We have a slack channel [`KampalR slack group`](http://kampalr.slack.com/) where we discuss all things R and also communicate about events happening. 
We have also introduced study jams where you can start from the basics all the way to your first R project.

KampalR is open to everyone that is interested in growing their data science journey and learning R. Novice, intermediate, expert it doesn’t matter what level you are at, join the community and let’s grow together.
We also have the ladies group [`@Rladieskampala`](https://twitter.com/Rladieskampala?s=17) where we can start our discussions with the latest hair style and plot the coolest graphs in R.
Want to learn more about the community and more stories from the community, follow me [`@nlimilimi`](http://twitter.com/nlimilimi) and follow [`@KampalR`](https://twitter.com/kampalR) to get the latest in the community.
