---
title: "Guidelines for creating an R User Group" 
author: "The leadership team"
date: 2020-06-02
categories: ["blog"]
tags: []
images: []
output:
  blogdown::html_page:
    toc: true
    toc_depth: 1
    number_sections: true
    fig_width: 16

links:
- icon: twitter
  icon_pack: fab
  name: Follow
  url: https://twitter.com/AfricaRUsers
    
---


AfricaR  supports the R community in Africa in the following ways:

+ Creation of new R User Groups. An R User Group (RUG), is a group of people who come together to learn R. These can be students studying in the same university or people who live/work in the same city. AfricaR provides guidelines and technical backup to facilitate the creation of new RUGs.

+ Publicizing R related work developed by Africans, on twitter via @[AfricaRUsers](https://twitter.com/AfricaRUsers).

+ Sharing course materials that people can use to either start out or advance in R. We are currently working on tutorials in french to assist members from the Francophone countries.

We have outlined a few steps that one could follow, to create a new RUG in their city.

**1. Create a leadership team**
<style>
body {text-align: justify}
</style>
If you are reading this guideline, it is probably because you want to create a R User Group in your city, meaning you will be the principal organizer of this RUG. We recommend that you really calculate the required time, involvement needed and the will to help people as a principal organizer of a local RUG, before jumping in. Leading an RUG involves teamwork, so you should consider creating a leadership team by finding 2 or 3 people that share your vision to create a local RUG. These people will help you to manage the RUG, especially when you need to take care of personal commitments. The leadership team should join the RUG organizers slack workspace, via [this link](https://rusergroups.slack.com/join/shared_invite/MjEyNDA3MzcyMjczLTE1MDAwMzU1MTgtODRjNGJlY2RiOA).


**2. Create social media accounts**

The R community is more alive on twitter,  than on any other social media. If you wish, you could create a twitter account for your RUG, naming it after your city eg @CityXRUG. To engage with the global R community, follow the #rstats hashtag.  You can find more information on how to engage with the R community on twitter, on [this link](https://aebou.rbind.io/posts/2017/12/how-to-follow-and-engage-with-the-r-community/) and on [this link](https://www.t4rstats.com/).
A page on meetup.com would help you too and you can open one for free on meetup.com. You can also create a facebook account to draw local peoples to your RUG. Feel free to work with any social media page that you deem fit. Also, please follow @[AfricaRUsers](https://twitter.com/AfricaRUsers) ,so that we can spread word about the new RUG.

**3. Getting financial assistance**

The R consortium, through its program to support RUGs, offers some financial aid and a meetup pro membership. You can find more information [on this website](https://www.r-consortium.org/) . Once you have a meetup account, please add your group [on this site](https://jumpingrivers.github.io/meetingsR/r-user-groups.html#middle-east-africa).

**4. Organizing meetup events**

Generally, when organizing  meetup events, two things need to be considered: a venue and speakers. We recommend that you get in touch with universities, co-working spaces and other spaces that you can have, for free. This will help you mitigate the costs that come with running events.    
The first event should be the launch event. Here, the leadership team would ideally introduce themselves to the participants. It would also be an opportunity to share the mission and vision of the RUG, and also inform people on the importance of learning R. You can also look for an external speaker, i.e someone who has been using R at work, for them to share their work experience with the participants. You can contact the [AfricaR leadership team](https://africa-r.org/contact/), in case you need help looking for a speaker. The first event should then be publicized on social media. This is ideally done via posters, that detail information such as event date and time, speaker profile and  topic of the event. You can reach out to the leadership team, so that we can help you create posters and also publicize the event on twitter. 
Please see the [R-Ladies Starter Kit](https://github.com/rladies/starter-kit/wiki/Organising-Events) for more ideas about planning the launch event and future events.


Incase you need further clarity, please do reach us through the [contact form](https://africa-r.org/contact/), or send us a direct email via _africarusers@gmail.com_.

Cheers!




